### ISSUE TITLE
Loop boxes do not always vertically surround the constituent calls correctly

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-js#1052]
Example (box is not tall enough):

![Image](https://user-images.githubusercontent.com/573108/220191996-b19ecea9-7db5-4e8b-aa45-d63ebaad71f6.png)

**Comment by brikelly** [comment]
Found in the Solidus map attached

[1676598908_493438_http_localhost_3000_cart_link.appmap.json.zip](https://github.com/getappmap/appmap-js/files/10787557/1676598908_493438_http_localhost_3000_cart_link.appmap.json.zip)

**Comment by ahtrotta** [comment]
Here's another example:



![Image](https://user-images.githubusercontent.com/45714532/220788593-24cb0917-6565-49c7-9e01-24fd1231d037.png)



After my fix:


![Image](https://user-images.githubusercontent.com/45714532/220788444-fc591e0e-5d04-4f5a-82f4-fee18d141370.png)



But if I select the element just below the loop box:


![Image](https://user-images.githubusercontent.com/45714532/220788325-8207fa61-5285-410f-b64b-7feac76b0803.png)

@brikelly I'm not sure how to reconcile this. Either the loop box is messed up, or the selection looks wonky. I know @kgilpin designed the sequence diagram so that there aren't return arrows when there's no return value, but I think if we put them in then this wouldn't be a problem.

**Comment by brikelly** [comment]
At a minimum fixing the first example where the box lines intersect untidily should be done before we release, it just looks broken. We can debate later if we should have all functions show return arrows to help with fixing this properly. 

FWIW I think we should have them unless it's a true one way call (ala something like an IPC call over UDP), because (a) it is confusing to not see return arrows from a function that blocks the caller for some time, and (b) because it'll help render these things properly.

**Comment by kgilpin** [comment]
There are really just two cases - has a return value and doesn’t have a
return value. Brian in your proposal the second case might still occur so
we’d handle it regardless - no?

In any case, I think that the third picture is actually pretty much fine. I
don’t see it as a significant problem. If you tighten up the bottom of the
loop box to the function call I don’t think it will look bad at all.

Probably more important is getting the z index right and also the line and
arrow origin and termination correct. You can see those being a bit off in
these images as well.

Overall, if this is what we have left to fix then we are good to go for an
initial release IMO. We are going to be our harshest critic. Users won’t
even notice - for quite a while anyway. They will care about: “does this
effectively map my code”

Are we thinking about that? At a higher level - are all the needed
interactions in place? Do they work intuitively? Are we using this on our
own code yet? If not then we don’t really have a strong basis to prioritize
anything except show stoppers - because we have neither internal nor
external users.

**Comment by brikelly** [comment]
The more I think of it the more I believe we should just show return arrows for all function calls, because it was super confusing to me when I saw them the first time. Plus it's what the UML spec says: only truly async calls where the caller is not blocked should be one way arrows. Sync calls that block the caller - even if there's no return data - should show a return arrow.

**Comment by ahtrotta** [comment]
@apotterri found an instance where this wasn't being handled



[1676376753_417918_http_localhost_8000_.appmap.zip](https://github.com/getappmap/appmap-js/files/10817195/1676376753_417918_http_localhost_8000_.appmap.zip)

**Comment by ahtrotta** [comment]
In the case where there is a loop box without a return arrow that is directly above another loop box, we have a problem. Currently, it looks like this:



![Image](https://user-images.githubusercontent.com/45714532/221019778-7fa47481-4cf7-4cba-984c-0dda6983a788.png)


If I make the top loop box occupy one extra grid row (see `grid-area` in the CSS), then it looks like this:



![Image](https://user-images.githubusercontent.com/45714532/221020009-7e0e8afc-e1f5-4e16-8d33-0d1c6dadaec4.png)

There's no way to avoid this unless we change how we render loops with only one function that doesn't have a return value.
