### ISSUE TITLE
Passing context items as "system" messages confuses the LLM about its purpose

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-js#1910]
When context items contain, for example, snippets of prompting, and the context items are passed as "system" messages (as they currently are), the LLM can get confused about its purpose, and start emitting output as if the context items were system directives.

It seems that it is better for context messages to be treated as user messages rather than system messages.

cc: @dustinbyrne

**Comment by kgilpin** [comment]
Here's an example in which even though I told it to `@generate`, it gives me a diagram. Changing the context items to `user` messages fixes the problem.

<img width="889" alt="Screen Shot 2024-07-25 at 1 17 51 PM" src="https://github.com/user-attachments/assets/89778034-529c-4fd9-ac65-3068e5270371">

**Comment by dustinbyrne** [comment]
The only gripe I have with providing context as a user prompt is that the LLM will often refer the context as user provided content. 

Here are a few examples I have in history from before it was moved to the system prompt:

> To write an RSpec test for `Activation::Request`, we need to focus on the behaviors depicted in the sequence diagrams and data requests you've provided.

> Let me outline the flow and key components involved in the signup and account activation process, referring to your provided code snippets and AppMap data.

> The code snippets you've provided indicate various aspects of a game client and server architecture, most likely from a Quake game.

As a user, it always felt somewhat unexpected because I haven't explicitly provided anything, it's been provided on my behalf. For what it's worth, code selections are still provided within the user prompt because this kind of language would be the expected behavior.

**Comment by dustinbyrne** [comment]
Shouldn't `@generate` take precedence as a mode selector?

**Comment by kgilpin** [comment]
Won't fix.
